site = https://raw.githubusercontent.com/ucb-stat159/stat159-fall-2016/master/projects/proj01/images/

all: images.png

images.png:
	curl $(site)/git-logo.png -o git-logo.png
	curl $(site)/github-logo.png -o github-logo.png
	curl $(site)/markdown-logo.png -o markdown-logo.png
	curl $(site)/pandoc-logo.png -o pandoc-logo.png
	curl $(site)/stat159-logo.png -o stat159-logo.png
